#!/usr/bin/env node
/**
 * Regenerates the static CV block in index.html from the same data the
 * interactive page renders (TRACKS, SKILLS, EVIDENCE, and the Background table).
 *
 * The static block is what prints, what shows with JavaScript off, and what a
 * crawler reads. It sits between the cv:start / cv:end markers.
 *
 *   node tools/build-cv.mjs           rewrite the block
 *   node tools/build-cv.mjs --check   exit 1 if the block is out of date
 *
 * The page itself still has no build step; this only keeps the copy in sync.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import vm from "node:vm";

const file = join(dirname(fileURLToPath(import.meta.url)), "..", "index.html");
const html = readFileSync(file, "utf8");

/* ---- pull the data out of the page's own script ---- */
function between(start, end) {
  const a = html.indexOf(start);
  const b = html.indexOf(end, a);
  if (a < 0 || b < 0) throw new Error(`markers not found: ${start} … ${end}`);
  return html.slice(a, b);
}
const code =
  between("var TRACKS = [", "/* ---------------- model") +
  between("var ALL = [", "function forTrack") +
  "\n;({ TRACK_NAME, SKILLS, EVIDENCE })";
const { SKILLS, EVIDENCE } = vm.runInNewContext(code);

/* ---- the Background & credentials table, rows verbatim ---- */
const bgStart = html.indexOf("Background &amp; credentials");
if (bgStart < 0) throw new Error("Background table not found");
const bgTable = html.slice(bgStart).match(/<table class="rec">([\s\S]*?)<\/table>/)[1];
const bgRows = [...bgTable.matchAll(/<tr><td>(.*?)<\/td><td>(.*?)<\/td><\/tr>/g)]
  .map(([, k, v]) => ({ k, v }));

/* ---- render ---- */
/* Lines that only make sense on the interactive page get a plain-print wording. */
const PRINT_WORDING = [
  [" — the same three signals scoring you right now.", "."],
];
const plain = (t) => PRINT_WORDING.reduce((s, [from, to]) => s.replace(from, to), t);

const esc = (s) =>
  String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

function record(r) {
  const bullets = r.b.map((x) => `        <li>${esc(plain(x.t))}</li>`).join("\n");
  const chips = [...new Set(r.c.map((x) => x.t))].join(" · ");
  const where = r.link
    ? `<a href="${esc(r.link)}">${esc(r.per)}</a>`
    : esc(r.per);
  return `    <div class="cv-rec">
      <h3>${esc(r.t)}</h3>
      <p class="cv-meta">${esc(r.o)} · ${where}</p>
      <ul>
${bullets}
      </ul>
      <p class="cv-chips">${esc(chips)}</p>
    </div>`;
}

const experience = EVIDENCE.filter((r) => !r.link);
const projects = EVIDENCE.filter((r) => r.link);
const skills = [...new Set(Object.values(SKILLS).flat())].join(" · ");

const bg = bgRows
  .map(({ k, v }) => `      <tr><th>${k}</th><td>${v}</td></tr>`)
  .join("\n");

const block = `<!-- cv:start — generated by tools/build-cv.mjs; edit the data in the page script, then re-run it -->
<article class="cv-static" id="cv">
  <div class="cv-head">
    <h1>Chetan Yadav</h1>
    <p class="cv-line">Delhi, India · <a href="mailto:chetan00yadav@gmail.com">chetan00yadav@gmail.com</a> · <a href="https://github.com/gtm-cyadav">github.com/gtm-cyadav</a></p>
    <p class="cv-intro">Built a lead scoring system for a GTM team — PostgreSQL, a logistic regression model and a Slack bot that alerts on hot leads. Marketing, market research and growth, with the data skills to back them up.</p>
  </div>

  <section>
    <h2>Experience</h2>
${experience.map(record).join("\n")}
  </section>

  <section>
    <h2>Projects</h2>
${projects.map(record).join("\n")}
  </section>

  <section>
    <h2>Skills</h2>
    <p class="cv-chips">${esc(skills)}</p>
  </section>

  <section>
    <h2>Education &amp; credentials</h2>
    <table class="cv-bg">
${bg}
    </table>
  </section>
</article>
<!-- cv:end -->`;

/* ---- splice between the markers ---- */
const re = /<!-- cv:start[\s\S]*?<!-- cv:end -->/;
if (!re.test(html)) throw new Error("cv:start / cv:end markers not found in index.html");
const next = html.replace(re, () => block);

if (process.argv.includes("--check")) {
  if (next !== html) {
    console.error("Static CV is out of date. Run: node tools/build-cv.mjs");
    process.exit(1);
  }
  console.log("Static CV is up to date.");
} else if (next === html) {
  console.log("Static CV already up to date.");
} else {
  writeFileSync(file, next);
  console.log("Static CV block rewritten.");
}
